server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/first?serverTimezone=Asia/Seoul
    username: jsh
    password: 1234
  devtools:
    livereload:
      enabled: true